Island rhythms/codemirror 5
mongoosejs/studio pull request #37
Opened 2024-06-14 14:42 UTC by IslandRhythms

Merge this and I'll then fix up the update code pr

2024-06-16 20:42 UTC, vkarpov15 requested changes

2024-06-16 20:42 UTC, vkarpov15 commented on frontend/src/create-document/create-document.js
> +    this.editor = CodeMirror.fromTextArea(this.$refs.codeEditor, {
Initial value doesn't seem to show up? In the following create modal, the value of `this.documentData` should show up

![image](https://github.com/mongoosejs/studio/assets/1620265/b762620f-99ad-41cb-8071-1828e9d98a1c)

2024-06-17 16:38 UTC, IslandRhythms commented
So apparently, if you use `fromTextArea`, it doesn't have the value property. Its only if you use `CodeMirror()` as a function that you can set an initial value.

2024-06-17 17:28 UTC, vkarpov15 approved these changes

2024-06-17 17:28 UTC, merged