ignore map paths
mongoosejs/studio pull request #4
Opened 2023-04-17 16:55 UTC by IslandRhythms

2023-04-17 21:30 UTC, vkarpov15 requested changes

2023-04-17 21:30 UTC, vkarpov15 commented on backend/helpers/removeSpecifiedPaths.js
> +      removeSpecifiedPaths(obj[key], paths);
Why does this need to be recursive? We don't drill into paths, so not really necessary.

2023-04-17 21:30 UTC, vkarpov15 commented on backend/actions/Model/getDocuments.js
> +  const schemaPaths = Model.schema.paths
Missing semicolon.

2023-04-17 21:30 UTC, vkarpov15 commented on backend/actions/Model/getDocument.js
> +  const schemaPaths = Model.schema.paths
Missing semi.

2023-04-17 21:34 UTC, IslandRhythms commented on backend/helpers/removeSpecifiedPaths.js
> +      removeSpecifiedPaths(obj[key], paths);
I blanked and was thinking that it went into the values, as opposed to just being headers

2023-04-21 20:03 UTC, vkarpov15 approved these changes

2023-04-21 20:04 UTC, merged