copy icon/functionality with tooltip
mongoosejs/studio pull request #7
Opened 2023-04-21 18:54 UTC by IslandRhythms

2023-04-21 20:06 UTC, vkarpov15 requested changes
One additional request, LGTM otherwise :+1:

2023-04-21 20:06 UTC, vkarpov15 commented on frontend/src/list-default/list-default.js
> +      elem.removeChild(storage);
Also add a vanilla toast with green checkmark that informs "Text has been copied to your clipboard"

2023-04-21 20:15 UTC, vkarpov15 requested changes

2023-04-21 20:15 UTC, vkarpov15 commented on frontend/src/list-default/list-default.js
> +      const elem = document.querySelector('#value-field');
Woops, I missed this. Do **not** rely on id, this will only work for the first list-default component on the page.

Use a Vue ref instead.

2023-04-21 21:03 UTC, IslandRhythms commented
![image](https://user-images.githubusercontent.com/39510674/233734213-a550999e-4bdb-4663-9e1c-bccddd2da969.png)
Vanilla toast is being weird

2023-04-24 01:50 UTC, vkarpov15 approved these changes

2023-04-24 01:50 UTC, merged